server:
  port: 9003    #微服务端口

spring:
  application:
    name: sentinel-provider-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   #nacos作为服务注册中心地址
management:
  endpoints:
    web:
      exposure:
        include: '*'