server:
  port: 3344

spring:
  application:
    name: config-center-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Xiao-Ning-166/springcloud-config.git  #github上存放配置的仓库的地址
          # 搜索目录
          search-paths:
            - springcloud-config
      # 搜索分支
      label: master

  # RabbitMQ相关配置
  rabbitmq:
    host: 192.168.254.100
    port: 5672
    username: admin
    password: admin

# 暴露 bus 刷新的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"

eureka:
  client:
    # 表示是否将自己注册进 Eureka Server。默认：true
    register-with-eureka: true
    # 是否从 EurekaServer 抓取已有的注册信息，默认为 true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   # 集群版
  instance:
    instance-id: config-center # eureka上显示的主机名称
    hostname: config-center