server:
  port: 2001  #微服务端口号
spring:
  application:
    name: seata-order-service   #微服务名称
  cloud:
    alibaba:
      seata:
        # 自定义事务组名称，需要与 seata conf/file.conf 中的设置对应
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #nacos作为服务注册中心的地址
  #数据库相关配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver  #数据库驱动包
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/seata_order_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

#激活 feign
feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 3000
  ConnectionTimeout: 3000

# 指定 sql映射文件的位置
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 打印 seata 的日志
logging:
  level:
    io:
      seata: info
