server:
  port: 80   # 微服务端口号

eureka:
  client:
    # 表示是否将自己注册进 Eureka Server。默认：true
    register-with-eureka: false
    # 是否从 EurekaServer 抓取已有的注册信息，默认为 true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   # 集群版

# 设置feign客户端超时时间（OpenFeign默认支持Ribbon）
ribbon:
  # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectionTimeout: 5000

# 开启 feign 的客户端
logging:
  level:
    # 指定 feign 以什么级别监控哪个接口
    edu.hue.springcloud.service.PaymentFeignService: debug
