server:
  port: 80  # 微服务地址

spring:
  application:
    name: consul-order-service
  cloud:
    consul:
      host: 192.168.254.100
      port: 8500
      discovery:
        hostname: 192.168.254.100
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true # 开启心跳机制